language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_script:
  - composer self-update
  - composer install --dev --prefer-source

script:
  - vendor/bin/phpunit -c ./phpunit.xml
  - sh -c "if [ '$TRAVIS_PHP_VERSION' != '5.3' ]; then ./vendor/bin/phpcs --standard=PSR2 ./src/; fi"

after_script:
  - mkdir -p build/logs
  - php vendor/bin/coveralls -v

notifications:
  irc: "irc.freenode.org#zftalk.modules"
  email: false
